### ISSUE TITLE
Term which starts with the following symbol is not supported: <<141>>

### ISSUE THREAD

**Issue by bigardone** [gaynetdinov/ex_marshal#25]
Hi 👋!
I'm using **ex_marshal** along with **memcachex** to read from a Memcached cache, shared with a Rails application. In this cache, there are records that have a field with a long avatar url, and when that field value exceeds a certain length it throws the following error:

```
** (ExMarshal.Errors.DecodeError) term which starts with the following symbol is not supported: <<141>>
    (ex_marshal) lib/ex_marshal/decoder.ex:63: ExMarshal.Decoder.decode_element/2
    (ex_marshal) lib/ex_marshal/decoder.ex:10: ExMarshal.Decoder.decode/1
```

In these cases, if I update the record from Rails with a shorter value, it works perfectly fine. What might be happening? Could it be something related to https://github.com/gaynetdinov/ex_marshal/pull/10? 
Thank you very much in advance :)

**Comment by gaynetdinov** [comment]
Hi!
Could you please provide the example of such string?

**Comment by gaynetdinov** [comment]
I just tried to run this test https://github.com/gaynetdinov/ex_marshal/pull/10/files#diff-29addc157c949c7ec3c85fb7a0a6911fR41 but with the string 20x times longer and it worked.
